In [5]:
import numpy as np

N-Dimension Arrays


In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [13]:
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.arange(0,12,3)

print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 3 6 9]


Indexing & slicing

In [15]:
arr=np.array([[10,20,30],[40,50,60]])

print(arr)
print(arr[0,1])
print(arr[:,1])
print(arr[0:2,1:3])

[[10 20 30]
 [40 50 60]]
20
[20 50]
[[20 30]
 [50 60]]


array operations

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a*b)
print(a**2)

[5 7 9]
[ 4 10 18]
[1 4 9]


Broadcasting

In [18]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [19]:
angles=np.array([0,np.pi/2,np.pi])
print(angles)

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Statistical functions

In [20]:
arr=np.array([1,2,3,4,5])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

3.0
3.0
1.4142135623730951
2.0
1
5


Shape manipulation

In [22]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr.reshape(3,2))
print(arr.flatten())
print(arr.ravel())
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


Joining and splitting arrays

In [24]:
a=np.array([[1,2]])
b=np.array([[3,4]])

print(np.concatenate((a,b),axis=0))
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2 3 4]]


In [25]:
arr = np.array([1,2,3,4,5,6])

print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]
